<a href="https://colab.research.google.com/github/avishek-astra/Deep_Learning_Experiments/blob/main/Ann_numparameter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
import torch.nn as nn

In [3]:
#build two models
widenet=nn.Sequential(
    nn.Linear(2,4), #hidden layer
    nn.Linear(4,3), #outputlayer
    )
deepnet=nn.Sequential(
    nn.Linear(2,2),#hidden layer
    nn.Linear(2,2),#hidden layer
    nn.Linear(2,3), #output layer
    )
#print them out to have a look
print(widenet)
print('')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)

Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


Peeking inside the network

In [4]:
#check out the parameters
for p in deepnet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[ 0.6404, -0.0179],
        [ 0.0342, -0.4927]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([-0.6988,  0.6361], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[0.1981, 0.6578],
        [0.3084, 0.6681]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.5172,  0.5833], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.2397,  0.4025],
        [ 0.4643,  0.1822],
        [ 0.5651, -0.1735]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([-0.0761, -0.2351,  0.5509], requires_grad=True))
 


In [5]:
#count the number of nodes(= the number of baises)
#named_parameters() is an iterable that returns the tuple(name, numbers)
numNodesInWide=0
for p in widenet.named_parameters():
  if 'bias' in p[0]: #p[0] the name of the parameter (string)
    numNodesInWide+=len(p[1]) #p[1]the parameter value (tensor)
numNodesInDeep=0
for p in deepnet.named_parameters():
  if 'bias' in p[0]:
    numNodesInDeep+=len(p[1])
print('THERE are %s node is wide network.'%numNodesInWide)
print('THERE are %s node is deep network.'%numNodesInDeep)

THERE are 7 node is wide network.
THERE are 7 node is deep network.


In [6]:
#just the parameters
for p in widenet.parameters():
  print(p)
  print(' ')

Parameter containing:
tensor([[-0.4012, -0.6508],
        [ 0.3156,  0.1606],
        [ 0.4066, -0.6197],
        [-0.4352,  0.1362]], requires_grad=True)
 
Parameter containing:
tensor([-0.1738,  0.0256, -0.2756,  0.6550], requires_grad=True)
 
Parameter containing:
tensor([[-0.2745,  0.3337, -0.0679,  0.0418],
        [-0.2155, -0.0312, -0.3987,  0.3577],
        [ 0.1124, -0.0528, -0.3524,  0.0894]], requires_grad=True)
 
Parameter containing:
tensor([0.1124, 0.2497, 0.2023], requires_grad=True)
 


In [7]:
#now count the total number of trainable parameters
nparams=0
for p in widenet.parameters():
  if p.requires_grad:
    print("This piece has %s parameters"%p.numel())
    nparams+=p.numel()
print('\n\n Total of %s parameters'%nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


 Total of 27 parameters


In [8]:
#A nice simple way to print out the model info.
from torchsummary import summary
summary(widenet,(1,2))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
