<a href="https://colab.research.google.com/github/avishek-astra/Deep_Learning_Experiments/blob/main/datasplit%2Ctrain%2Ctest%2Cdev.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#importing libraries
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from IPython import display
display.set_matplotlib_formats('svg')
#NEW!
from sklearn.model_selection import train_test_split

<ipython-input-1-167363004367>:7: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  display.set_matplotlib_formats('svg')


In [2]:
#create our fake dataset
fakedata=np.tile(np.array([1,2,3,4]),(10,1))+np.tile(10*np.arange(1,11),(4,1)).T
fakelabels=np.arange(10)>4
print(fakedata),print(' ')
print(fakelabels)

[[ 11  12  13  14]
 [ 21  22  23  24]
 [ 31  32  33  34]
 [ 41  42  43  44]
 [ 51  52  53  54]
 [ 61  62  63  64]
 [ 71  72  73  74]
 [ 81  82  83  84]
 [ 91  92  93  94]
 [101 102 103 104]]
 
[False False False False False  True  True  True  True  True]


In [4]:
#specify sizes of the partitions
#order is train, devset, test
partitions=[.8,.1,.1]
#split the data( note the third input, and the TMP in the variable name)
train_data,testTMP_data,train_labels,testTMP_labels=train_test_split(fakedata,fakelabels,train_size=partitions[0])
#now split the TMP data
split=partitions[1]/(partitions[1]+partitions[2])
devset_data,test_data,devset_labels,test_labels=train_test_split(testTMP_data,testTMP_labels,train_size=split)
#print out the train/test data
print('Training data: ')
print(train_data)
print(' ')
print('Devset data: ')
print(devset_data)
print(' ')
print('Test data: ')
print(test_data)

Training data: 
[[ 21  22  23  24]
 [101 102 103 104]
 [ 31  32  33  34]
 [ 41  42  43  44]
 [ 81  82  83  84]
 [ 51  52  53  54]
 [ 11  12  13  14]
 [ 61  62  63  64]]
 
Devset data: 
[[71 72 73 74]]
 
Test data: 
[[91 92 93 94]]
