<a href="https://colab.research.google.com/github/avishek-astra/Deep_Learning_Experiments/blob/main/data_datasetLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import libraries
import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset

Datasets

In [2]:
#create some data in numpy
nObservations=100
nFeatures=20
data=np.random.randn(nObservations,nFeatures)

In [4]:
#convert to pytorch tensor
dataT=torch.tensor(data)
#print out some information
print('Name data: ')
print(type(data))
print(data.shape)
print(data.dtype)
print(" ")

print('Tensor data:')
print(type(dataT))
print(dataT.size())
print(dataT.dtype)
print(' ')

Name data: 
<class 'numpy.ndarray'>
(100, 20)
float64
 
Tensor data:
<class 'torch.Tensor'>
torch.Size([100, 20])
torch.float64
 


In [5]:
#sometimes you need to convert data types
dataT2=torch.tensor(data).float()
print(dataT2.dtype)
#'long' is for ints
dataT3=torch.tensor(data).long()
print(dataT3.dtype)

torch.float32
torch.int64


In [12]:
#convert tensor into Pytorch Datasets
dataset=TensorDataset(dataT)
#dataset is a two element tuple comprising data, labels
dataset.tensors[0]

tensor([[-1.1952, -0.1575, -1.4097,  ...,  0.9337, -0.7092, -1.5328],
        [-0.8140, -0.4005,  1.6873,  ..., -1.2725,  0.3227,  0.9844],
        [ 0.1882, -0.8809, -0.2159,  ...,  1.2647, -0.4740,  1.5368],
        ...,
        [ 0.9333, -1.5323,  1.8081,  ..., -0.4900, -0.8651,  1.0613],
        [-0.2091, -1.8843, -0.2280,  ...,  0.3114, -0.8840, -0.3980],
        [ 0.1206,  0.2440, -1.1332,  ..., -0.3964, -0.7763, -0.7662]],
       dtype=torch.float64)

In [13]:
#let's try again with labels
labels=torch.ceil(torch.linspace(.01,4,nObservations))
#transform to an actual matrix (column vector)
labels=labels.reshape((len(labels),1))
#now make another dataset
dataset=TensorDataset(dataT,labels)
print(dataset.tensors[0].shape)
print(dataset.tensors[1].shape)

torch.Size([100, 20])
torch.Size([100, 1])


Dataloaders

In [14]:
batchsize=25
dataloader=DataLoader(dataset,batch_size=batchsize)
dataloader.dataset.tensors[0].size()

torch.Size([100, 20])

In [15]:
for dat,labs in dataloader:
  print('BATCH INFO:')
  print(dat.size())
  print(labs.size())
  print(' ')

BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 


In [16]:
#inspect the labels
for dat, labs in dataloader:
  print(labs.T)
  print(' ')


tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.]])
 
tensor([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2.]])
 
tensor([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3.]])
 
tensor([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4., 4., 4., 4., 4., 4.]])
 


In [18]:
#try again with shuffling(shuffling happens during iteration)
dataloader=DataLoader(dataset,batch_size=batchsize,shuffle=True)
for data,labs in dataloader:
  print(labs.T)
  print(' ')

tensor([[4., 2., 3., 1., 4., 1., 1., 3., 2., 2., 1., 4., 4., 3., 3., 1., 1., 2.,
         1., 2., 4., 3., 3., 1., 4.]])
 
tensor([[1., 2., 1., 4., 2., 3., 2., 3., 3., 4., 2., 3., 4., 1., 4., 3., 3., 1.,
         3., 2., 1., 1., 1., 1., 3.]])
 
tensor([[2., 3., 4., 3., 2., 4., 1., 3., 3., 2., 2., 2., 4., 2., 2., 1., 4., 1.,
         1., 2., 1., 4., 4., 2., 2.]])
 
tensor([[1., 3., 4., 4., 3., 2., 2., 4., 1., 4., 1., 4., 2., 3., 4., 3., 1., 2.,
         2., 3., 4., 3., 4., 3., 4.]])
 
