<a href="https://colab.research.google.com/github/avishek-astra/Deep_Learning_Experiments/blob/main/Dropoutregularization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import libraries
import torch
import torch.nn as nn
import torch.nn.functional as F

Using dropout

In [12]:
#define a dropout instance and make some data
prob=0.5
dropout=nn.Dropout(p=prob)
x=torch.ones(10)
#let's see what dropout return returns
print(x)
y=dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([2., 0., 0., 2., 0., 2., 2., 0., 0., 2.])
tensor(1.)


In [13]:
#dropout is turned off when evaluating the model
dropout.eval()
y=dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [14]:
#annoyingly, F.dropout() is not activated in eval mode:
dropout.eval()
y=F.dropout(x)
print(y)
print(torch.mean(y))

tensor([0., 2., 0., 2., 0., 0., 2., 2., 0., 2.])
tensor(1.)


In [15]:
#but you can manually switch it off
dropout.eval()
y=F.dropout(x, training=False)
print(y)
print(torch.mean(y))


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [17]:
#the model needs to be reset after toggling into eval mode
dropout.train()
y=dropout(x)
print(y) #with dropout
dropout.eval()
y=dropout(x)
print(y) #without dropout
dropout.train()
y=dropout(x)
print(y) #with dropout

tensor([2., 2., 2., 2., 2., 2., 2., 0., 2., 0.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([2., 2., 0., 2., 0., 2., 0., 2., 2., 2.])
